"""empty message

Revision ID: 63ab5536a804
Revises: 
Create Date: 2019-10-29 14:34:11.809990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ab5536a804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_info_log',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('leave_time', sa.DateTime(), nullable=False),
    sa.Column('online_minute', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('city_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_info_log')
    # ### end Alembic commands ###
